name: Forecast build and deploy

on:
  schedule:
    - cron: "*/15 * * * *"    # every 15 minutes (UTC)
  workflow_dispatch: {}        # manual trigger for testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        working-directory: Forecast/src
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run forecast generator
        working-directory: Forecast/src
        env:
          PYTHONWARNINGS: "ignore::FutureWarning:cfgrib.xarray_plugin"
        run: python -u main.py

      - name: Stage JSON into public_html
        run: |
          mkdir -p public_html/Forecast/data
          rsync -a --delete Forecast/src/data/ public_html/Forecast/data/

      - name: Commit and push artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add public_html/Forecast/data
          git commit -m "auto: forecast update [skip ci]" || echo "no changes"
          git push

      - name: Trigger Cloudways deploy webhook
        run: |
          curl -sS -X GET "${{ secrets.CW_DEPLOY_URL }}"
