name: Forecast Job

on:
  schedule:
    - cron: "*/15 * * * *"      # run every 15 minutes
  workflow_dispatch:            # allow manual runs

# Prevent overlapping runs if a previous 15-min job is still going
concurrency:
  group: forecast-job
  cancel-in-progress: false

permissions:
  contents: write               # required to commit/push JSON

jobs:
  run-forecast:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Forecast/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # cfgrib needs the ecCodes C libraries
      - name: Install system libs for cfgrib/ecCodes
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libeccodes0 libeccodes-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r Forecast/requirements.txt

      - name: Run forecast
        env:
          # mirror your local suppression for cfgrib warnings
          PYTHONWARNINGS: "ignore::FutureWarning:cfgrib.xarray_plugin"
        run: |
          python Forecast/src/main.py

      - name: Stage JSON into public_html
        run: |
          mkdir -p public_html/Forecast/data/
          shopt -s nullglob
          # copy common output locations; adjust if your script writes elsewhere
          for f in Forecast/data/*.json Forecast/data/wave-forecast/*.json; do
            cp "$f" public_html/Forecast/data/
          done

      - name: Commit & push JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public_html/Forecast/data/ || true
          git commit -m "Update forecast JSON [skip ci]" || echo "No changes to commit"
          git push

      # 🔔 Cloudways pull trigger (robust; no fragile long URL in secrets)
      - name: Trigger Cloudways pull (webhook)
        env:
          CW_DEPLOY_BASE: ${{ secrets.CW_DEPLOY_BASE }} # e.g. https://phpstack-1452178-5683884.cloudwaysapps.com/gitautodeploy.php
          CW_SERVER_ID: "1452178"
          CW_APP_ID: "5683884"
          GIT_URL: "git@github.com:AustinLegenda/AustinLegenda-refract.git"
          BRANCH: "main"
        run: |
          BASE="$(printf %s "$CW_DEPLOY_BASE" | tr -d '\r\n')"
          if [ -z "$BASE" ]; then
            echo "::error::CW_DEPLOY_BASE secret is not set"; exit 1
          fi

          echo "Calling Cloudways webhook…"
          # Build the query safely; curl handles encoding of @ : / etc.
          curl -sS -m 60 --get "$BASE" \
            --data-urlencode "server_id=$CW_SERVER_ID" \
            --data-urlencode "app_id=$CW_APP_ID" \
            --data-urlencode "git_url=$GIT_URL" \
            --data-urlencode "branch_name=$BRANCH" \
            -D /tmp/cw.headers -o /tmp/cw.json || {
              echo "::error::Failed to reach Cloudways webhook"; exit 1;
            }

          echo "HTTP status: $(head -n1 /tmp/cw.headers)"
          echo "Cloudways response:"
          cat /tmp/cw.json || true

          # Soft check: if the response contains the string "error", surface it.
          if grep -qi '"error"' /tmp/cw.json 2>/dev/null; then
            echo "::error::Cloudways returned an error payload"
            exit 1
          fi
